### ISSUE TITLE
fix spelling

### ISSUE THREAD

**Issue by schettino72** [pydoit/doit-tmp-doc#1]
on doit docs:

- the spell checker uses a `dictionary.txt` file where you can put words that you want to spell checker to ignore.
- I also put most python code in separate files, so the spell checker is not run on code. (also advantage of being able to run pyflakes on docs snippets.

**Comment by vlcinsky** [comment]
I am aware of spelling not being perfect. My priority was to collect ideas and draft the outline first and spelling was getting too often into my way.

But the time for proper spelling comes. I will modify it.

**Comment by vlcinsky** [comment]
Fixed all spelling errors.

However, i am not sure, if I did it properly as I simply added into dictionary.txt all what was acceptable but in many cases there were:
- thing from code
- split keywords, e,g. "dep" originating from "file_dep"

If there is any way to mark these things better or in place, I would try, otherwise we can close it.

**Comment by vlcinsky** [comment]
I think I got an idea for spelling solution.

https://pypi.python.org/pypi/sphinxcontrib-spelling/2.3.0

It shall be aware of complete documentation structure, code, other text components, and even allow listing special acceptable terms within rst files.

I have used it in past (with little problem to spell Czech text, but fixed that). I will try.

**Comment by vlcinsky** [comment]
Spelling modified to use `sphinxcontrib.spelling`.

However, it requires package `libenchant1c2a` to be installed. On ubuntu I usually do: `sudo apt-get install libenchant1c2a` but I have no idea, where to put it into ci-circle configuration file.

**Comment by vlcinsky** [comment]
Differences from original spelling solution:
- sphinx one better recognize free text and special constructs (as code listing, keywords, variables) so it does not report so many false positives. `dictionary.txt` shrinked from 96 lines down to 17.
- it has a bit different dependencies (I think).
- it is run as new target. Some instructions say to use `$ make spell` but I it fails on my box.
- spelling is now managed via `sphinx-build -b spell` as shown in `dodo.py`. It works well for me.

`conf.py` currently declares `spelling_language="en_GB"` as this is my preferred one (over US).
